### ISSUE TITLE
请教大神 LameUtil.init（）方法老是报错

### ISSUE THREAD

**Issue by CatyVon** [CrazyZty/ComposeAudio#7]
我在自己的项目中继承了demo的合成方法  目前背景音跟录的音都可以转换成pcm格式  但是在调用 AudioFunction.ComposeAudio()方法的时候  老是会在  LameUtil.init（）处出现闪退  因为项目中使用了录音打分sdk  所以项目中已经导入了libmp3lame.so文件  我用你上传的demo中so文件替换了之前同文件夹的so  但是还是出在Lameutil.init（）方法出崩溃  请教大神解决思路  

Log如下
05-17 17:44:33.440 20576-20766/? E/刷新error日志文件输出流出错: java.lang.NullPointerException
05-17 17:44:33.443 20576-20766/? E/AppLog:打印error数据异常: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.write(java.lang.String)' on a null object reference
05-17 17:44:33.447 20576-20766/? E/zygote64: No implementation found for void com.harmight.dubbing.utils.LameUtil.init(int, int, int, int, int) (tried Java_com_harmight_dubbing_utils_LameUtil_init and Java_com_harmight_dubbing_utils_LameUtil_init__IIIII)
05-17 17:44:33.448 20576-20766/? E/AndroidRuntime: FATAL EXCEPTION: Thread-54
    Process: com.harmight.dubbing, PID: 20576
    java.lang.UnsatisfiedLinkError: No implementation found for void com.harmight.dubbing.utils.LameUtil.init(int, int, int, int, int) (tried Java_com_harmight_dubbing_utils_LameUtil_init and Java_com_harmight_dubbing_utils_LameUtil_init__IIIII)
        at com.harmight.dubbing.utils.LameUtil.init(Native Method)
        at com.harmight.dubbing.utils.AudioFunction.ComposeAudio(AudioFunction.java:62)
        at com.harmight.dubbing.utils.AudioFunction.BeginComposeAudio(AudioFunction.java:23)
        at com.harmight.dubbing.ui.DubbingActivity.decode_compose(DubbingActivity.java:280)
        at com.harmight.dubbing.ui.DubbingActivity.access$000(DubbingActivity.java:95)
        at com.harmight.dubbing.ui.DubbingActivity$1.run(DubbingActivity.java:243)
        at java.lang.Thread.run(Thread.java:764)

**Comment by CrazyZty** [comment]
这个问题看起来像是 JNI 调用有问题，你用的 libmp3lame.so 和我项目的不一样，jni 缺少 Java_com_harmight_dubbing_utils_LameUtil_init 这个方法，你改一下初始化代码， jni 处用你的 libmp3lame.so 的初始化代码吧。

**Comment by zhangxin1989** [comment]
请问有libmp3lame.so 的源码么，现在直接用你提供的这个我需要包名保持com.czt.mp3recorder.util这个才行

**Comment by plmmanwu** [comment]
包名换成这个也不行 有其他解决办法吗
